services:
  - type: web
    name: smooth-telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: NEWS_API_KEY
        sync: false
      - key: GROUP_CHAT_IDS
        sync: false
      - key: PORT
        value: 8000
